CREATE DATABASE IF NOT EXISTS master;

USE master;

CREATE TABLE IF NOT EXISTS users
(
	ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME varchar(100)   NOT NULL,
	LAST_NAME varchar(100)    NOT NULL,
	EMAIL varchar(100)        NOT NULL,
	USERNAME varchar(50)      NOT NULL,
	PASSWORD varchar(50)      NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS listride 
(
  ID MEDIUMINT  NOT NULL AUTO_INCREMENT,
  NAME varchar(100)          NOT NULL,
  EMAIL varchar(100)         NOT NULL,
  ORIGIN varchar(200)        NOT NULL,
  DESTINATION varchar(200)   NOT NULL,
  LEAVING_DATE varchar(15)   NOT NULL,
  LEAVING_TIME varchar(20)   NOT NULL
);